// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RH_DO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250704161925_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("AdjuntoCorreo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchivoPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Adjuntos");
                });

            modelBuilder.Entity("Analista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre_ANA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Analistas");
                });

            modelBuilder.Entity("Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Analista")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido_Materno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido_Paterno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrera")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contrato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado_Induccion_Cultural")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_Induccion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_Induccion_Cultural")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_Ingreso")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_Nacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gerencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gerencia_mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jefe_Directo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RUT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sociedad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticket")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_de_Contrato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Universidad")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Gerencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre_GER")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gerencias");
                });

            modelBuilder.Entity("Sociedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre_SOC")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sociedades");
                });

            modelBuilder.Entity("Ubicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre_UBI")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
