// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RH_DO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250725150420_NotificacionesPost")]
    partial class NotificacionesPost
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("AdjuntoCorreo", b =>
                {
                    b.Property<int>("Id_AC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchivoPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_Adjunto")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_AC");

                    b.ToTable("AdjuntosCorreos");
                });

            modelBuilder.Entity("AdjuntoCorreo_post", b =>
                {
                    b.Property<int>("Id_AC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArchivoPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_Adjunto")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_AC");

                    b.ToTable("AdjuntoCorreo_post");
                });

            modelBuilder.Entity("Analista", b =>
                {
                    b.Property<int>("Id_ANA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre_ANA")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_ANA");

                    b.ToTable("Analistas");
                });

            modelBuilder.Entity("CorreoEnviado_POST", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailDestinatario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("TEXT");

                    b.Property<string>("RUT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoCorreo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CorreosEnviados_POST");
                });

            modelBuilder.Entity("DestinatariosCorreo_POST", b =>
                {
                    b.Property<int>("Id_DCP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CCFijos")
                        .HasColumnType("TEXT");

                    b.Property<string>("CCOFijos")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinatariosFijos")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo_DCP")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_DCP");

                    b.ToTable("DestinatariosCorreo_POST");
                });

            modelBuilder.Entity("DestinatariosCorreo_PRE", b =>
                {
                    b.Property<int>("Id_DCP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CCFijos")
                        .HasColumnType("TEXT");

                    b.Property<string>("CCOFijos")
                        .HasColumnType("TEXT");

                    b.Property<string>("DestinatariosFijos")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo_DCP")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_DCP");

                    b.ToTable("DestinatariosCorreo_PRE");
                });

            modelBuilder.Entity("Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Analista")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido_Materno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Apellido_Paterno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cargo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrera")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contrato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Correo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado_Induccion_Cultural")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_Induccion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_Induccion_Cultural")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_Ingreso")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Fecha_Nacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gerencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gerencia_mail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jefe_Directo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RUT")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sociedad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ticket")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo_de_Contrato")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Universidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioModifico")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Gerencia", b =>
                {
                    b.Property<int>("Id_GER")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre_GER")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_GER");

                    b.ToTable("Gerencias");
                });

            modelBuilder.Entity("PlantillaCorreo", b =>
                {
                    b.Property<int>("Id_PC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HtmlContenido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_PC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo_PC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_PC");

                    b.ToTable("PlantillasCorreos");
                });

            modelBuilder.Entity("PlantillaCorreo_POST", b =>
                {
                    b.Property<int>("Id_PC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HtmlContenido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre_PC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo_PC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_PC");

                    b.ToTable("PlantillaCorreo_POST");
                });

            modelBuilder.Entity("Sociedad", b =>
                {
                    b.Property<int>("Id_SOC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre_SOC")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_SOC");

                    b.ToTable("Sociedades");
                });

            modelBuilder.Entity("SolicitudEdicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Aprobada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatosAnteriores")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatosSolicitados")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaProcesamiento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Procesada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RutEmpleado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioProceso")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioSolicitante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SolicitudesEdicion");
                });

            modelBuilder.Entity("Ubicaciones", b =>
                {
                    b.Property<int>("Id_UBI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre_UBI")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_UBI");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
